import json
import logging
import os
import sqlite3

from bot.core.prompts import EXTRACT_PROMPT

logger = logging.getLogger(__name__)

CREATE_SQL = """
CREATE TABLE IF NOT EXISTS user_memories (
    user_id TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (user_id, key)
)
"""

UPSERT_SQL = """
INSERT INTO user_memories (user_id, key, value, updated_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(user_id, key) DO UPDATE SET
    value = excluded.value,
    updated_at = datetime('now')
"""


class MemoryStore:
    """Persistent kv store for cross-session user memories.

    Each memory is ``(user_id, key, value)`` stored in a dedicated
    ``user_memories`` table. Keys are semantic labels generated by the
    LLM (e.g. ``"名字"``, ``"喜欢的食物"``).
    """

    EXTRACT_PROMPT = EXTRACT_PROMPT

    def __init__(self, db_path: str | None = None) -> None:
        if db_path is None:
            db_dir = os.getenv("BOT_DB_DIR", "db")
            db_path = os.path.join(db_dir, "memory.sqlite")
        self.db_path = db_path
        self._conn: sqlite3.Connection | None = None
        self._init_db()

    @property
    def conn(self) -> sqlite3.Connection:
        if self._conn is None:
            self._conn = sqlite3.connect(self.db_path)
            self._conn.row_factory = sqlite3.Row
        return self._conn

    def _init_db(self) -> None:
        self.conn.execute(CREATE_SQL)
        self.conn.commit()
        logger.info("MemoryStore ready (db=%s)", self.db_path)

    def load_memories(self, user_id: str) -> list[dict]:
        rows = self.conn.execute(
            "SELECT key, value FROM user_memories WHERE user_id = ? ORDER BY updated_at DESC",
            (user_id,),
        ).fetchall()
        return [{"key": row["key"], "value": row["value"]} for row in rows]

    def store_memory(self, user_id: str, key: str, value: str) -> None:
        self.conn.execute(UPSERT_SQL, (user_id, key, value))
        self.conn.commit()

    def store_memories(self, user_id: str, memories: list[dict]) -> None:
        for m in memories:
            self.conn.execute(UPSERT_SQL, (user_id, m["key"], m["value"]))
        self.conn.commit()

    def delete_memory(self, user_id: str, key: str) -> None:
        self.conn.execute(
            "DELETE FROM user_memories WHERE user_id = ? AND key = ?",
            (user_id, key),
        )
        self.conn.commit()

    def clear_user_memories(self, user_id: str) -> None:
        self.conn.execute("DELETE FROM user_memories WHERE user_id = ?", (user_id,))
        self.conn.commit()

    def format_memories(self, user_id: str) -> str:
        memories = self.load_memories(user_id)
        if not memories:
            return ""
        return "\n".join(f"- {m['key']}：{m['value']}" for m in memories)

    def close(self) -> None:
        if self._conn is not None:
            self._conn.close()
            self._conn = None

    @classmethod
    def parse_extraction(cls, raw: str) -> list[dict]:
        cleaned = raw.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.strip("`").removeprefix("json").strip()
        memories = json.loads(cleaned)
        if not isinstance(memories, list):
            return []
        return [m for m in memories if "key" in m and "value" in m]
