"""用户记忆存储：对齐 langgraph 官方 BaseStore 体系。

持久记忆用官方 ``AsyncSqliteStore``（继承 ``BaseStore`` 的官方 sqlite 后端，
``langgraph.store.sqlite``，数据落 ``db/memory.sqlite`` 的 ``store`` 表）。
本类作为薄封装，把旧的 ``(user_id, key)`` 二维键映射到官方 namespace
``("user", user_id)`` + key，value 统一序列化为 ``{"value": <str>}`` dict。

连接惰性建立（首次操作时），方法全 async（官方 store 是异步接口），
不再需要工具层手动 ``asyncio.to_thread`` 包装。
"""

import asyncio
import logging
import os

import aiosqlite
from langgraph.store.sqlite import AsyncSqliteStore

logger = logging.getLogger(__name__)

_NAMESPACE = "user"  # namespace 第一段；第二段是 user_id（QQ 号，纯数字，符合官方 namespace 字符集）
_MAX_MEMORIES = 1000  # asearch 无 index 时的单次返回上限（单用户记忆量远小于此）


class MemoryStore:
    """langgraph BaseStore 后端的按用户维度持久 kv 记忆。

    Each memory is ``(user_id, key, value)`` stored as
    ``store[("user", user_id)][key] = {"value": value}``. Keys are semantic
    labels generated by the LLM (e.g. ``"名字"``, ``"喜欢的食物"``).
    """

    def __init__(self, db_dir: str = "db") -> None:
        self.db_path = os.path.join(db_dir, "memory.sqlite")
        self._conn: aiosqlite.Connection | None = None
        self._store: AsyncSqliteStore | None = None
        self._init_lock = asyncio.Lock()

    @staticmethod
    def _ns(user_id: str) -> tuple[str, ...]:
        return (_NAMESPACE, user_id)

    async def _ensure(self) -> AsyncSqliteStore:
        """惰性建立连接 + AsyncSqliteStore + 迁移旧数据；并发首调用互斥。"""
        async with self._init_lock:
            if self._store is None:
                conn = await aiosqlite.connect(self.db_path, isolation_level=None)
                store = AsyncSqliteStore(conn)
                await store.setup()
                self._conn = conn
                self._store = store
                await self._migrate_legacy()
                logger.info(
                    "MemoryStore ready (db=%s, backend=langgraph AsyncSqliteStore)",
                    self.db_path,
                )
        return self._store

    async def _migrate_legacy(self) -> None:
        """一次性迁移旧 ``user_memories`` 表 → 官方 ``store`` 表。

        迁移成功后 DROP 旧表，幂等（表不存在即跳过）；中途失败下次启动重试，
        重复 aput 为覆盖写不产生脏数据。迁移只为保留真实用户记忆，非功能路径。
        """
        cur = await self._conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='user_memories'"
        )
        exists = (await cur.fetchone()) is not None
        await cur.close()
        if not exists:
            return
        rows = await self._conn.execute_fetchall(
            "SELECT user_id, key, value FROM user_memories"
        )
        for user_id, key, value in rows:
            await self._store.aput(self._ns(user_id), key, {"value": value})
        await self._conn.execute("DROP TABLE user_memories")
        logger.info("Migrated %d legacy user memories to langgraph store", len(rows))

    async def load_memories(self, user_id: str) -> list[dict]:
        store = await self._ensure()
        items = await store.asearch(self._ns(user_id), limit=_MAX_MEMORIES)
        items.sort(key=lambda i: i.updated_at, reverse=True)
        return [{"key": i.key, "value": i.value.get("value", "")} for i in items]

    async def store_memory(self, user_id: str, key: str, value: str) -> None:
        store = await self._ensure()
        await store.aput(self._ns(user_id), key, {"value": value})

    async def delete_memory(self, user_id: str, key: str) -> None:
        store = await self._ensure()
        await store.adelete(self._ns(user_id), key)

    async def clear_user_memories(self, user_id: str) -> None:
        store = await self._ensure()
        for item in await store.asearch(self._ns(user_id), limit=_MAX_MEMORIES):
            await store.adelete(self._ns(user_id), item.key)

    async def format_memories(self, user_id: str) -> str:
        memories = await self.load_memories(user_id)
        if not memories:
            return ""
        return "\n".join(f"- {m['key']}：{m['value']}" for m in memories)

    async def close(self) -> None:
        async with self._init_lock:
            if self._conn is not None:
                # AsyncSqliteStore 自身无 aclose（__aexit__ 仅停 TTL sweeper），
                # 官方用法即关闭底层 aiosqlite 连接。
                await self._conn.close()
                self._conn = None
                self._store = None
