import json
import logging
import sqlite3

logger = logging.getLogger(__name__)

CREATE_SQL = """
CREATE TABLE IF NOT EXISTS user_memories (
    user_id TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (user_id, key)
)
"""

UPSERT_SQL = """
INSERT INTO user_memories (user_id, key, value, updated_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(user_id, key) DO UPDATE SET
    value = excluded.value,
    updated_at = datetime('now')
"""


class MemoryStore:
    """Persistent kv store for cross-session user memories.

    Each memory is ``(user_id, key, value)`` stored in a dedicated
    ``user_memories`` table. Keys are semantic labels generated by the
    LLM (e.g. ``"名字"``, ``"喜欢的食物"``).
    """

    def __init__(self, db_path: str = "bot_memory.sqlite") -> None:
        self.db_path = db_path
        self._conn: sqlite3.Connection | None = None
        self._init_db()

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    @property
    def conn(self) -> sqlite3.Connection:
        if self._conn is None:
            self._conn = sqlite3.connect(self.db_path)
            self._conn.row_factory = sqlite3.Row
        return self._conn

    def _init_db(self) -> None:
        self.conn.execute(CREATE_SQL)
        self.conn.commit()
        logger.info("MemoryStore ready (db=%s)", self.db_path)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def load_memories(self, user_id: str) -> list[dict]:
        """Load all memories for a user as ``[{key, value}, ...]``."""
        rows = self.conn.execute(
            "SELECT key, value FROM user_memories WHERE user_id = ? ORDER BY updated_at DESC",
            (user_id,),
        ).fetchall()
        return [{"key": row["key"], "value": row["value"]} for row in rows]

    def store_memory(self, user_id: str, key: str, value: str) -> None:
        """Upsert a single memory entry."""
        self.conn.execute(UPSERT_SQL, (user_id, key, value))
        self.conn.commit()

    def store_memories(self, user_id: str, memories: list[dict]) -> None:
        """Upsert multiple memories in one transaction."""
        for m in memories:
            self.conn.execute(UPSERT_SQL, (user_id, m["key"], m["value"]))
        self.conn.commit()

    def delete_memory(self, user_id: str, key: str) -> None:
        """Delete a specific memory for a user."""
        self.conn.execute(
            "DELETE FROM user_memories WHERE user_id = ? AND key = ?",
            (user_id, key),
        )
        self.conn.commit()

    def clear_user_memories(self, user_id: str) -> None:
        """Delete all memories for a user."""
        self.conn.execute("DELETE FROM user_memories WHERE user_id = ?", (user_id,))
        self.conn.commit()

    def format_memories(self, user_id: str) -> str:
        """Load and format memories as human-readable text."""
        memories = self.load_memories(user_id)
        if not memories:
            return ""
        return "\n".join(f"- {m['key']}：{m['value']}" for m in memories)

    def close(self) -> None:
        if self._conn is not None:
            self._conn.close()
            self._conn = None

    # ------------------------------------------------------------------
    # Extraction helpers
    # ------------------------------------------------------------------

    EXTRACT_PROMPT = """你是一个信息提取助手。从对话中提取用户提到的持久性个人信息。

对话：
用户: {user_message}
Bot: {bot_reply}

要求：
- 只提取持久性的事实（名字、偏好、习惯、背景等个人信息）
- 不要提取一次性事件、临时状态或对话无关内容
- 如果用户提到了自己的信息（自我介绍、喜好等），才需要提取
- 如果 Bot 在询问用户信息，用户的回答需要提取

输出格式：JSON 数组，每项包含 "key" 和 "value" 字段
示例：[{{"key": "名字", "value": "张三"}}, {{"key": "喜欢的食物", "value": "火锅"}}]
如果没有新信息，返回 []"""

    @classmethod
    def parse_extraction(cls, raw: str) -> list[dict]:
        """Parse LLM extraction response into structured memories."""
        cleaned = raw.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.strip("`").removeprefix("json").strip()
        memories = json.loads(cleaned)
        if not isinstance(memories, list):
            return []
        return [m for m in memories if "key" in m and "value" in m]
