"""Satori 协议平台适配（显式导出，无 `__getattr__` 懒加载魔法）。

与项目“显式导入、单一源”的治理约定一致：所有协议模型 / 传输客户端 / 事件
归一化在此一次性显式导出，避免 ``_module_map`` + ``__getattr__`` 的动态重导出。
``adapter`` 直接导入子模块（``events`` / ``http``），不依赖包级门面，因此无
导入顺序约束。
"""

from .adapter import SatoriAdapter
from .api import (
    CHANNEL_CREATE,
    CHANNEL_DELETE,
    CHANNEL_GET,
    CHANNEL_LIST,
    CHANNEL_MUTE,
    CHANNEL_UPDATE,
    FRIEND_APPROVE,
    FRIEND_DELETE,
    FRIEND_LIST,
    GUILD_APPROVE,
    GUILD_GET,
    GUILD_LIST,
    GUILD_MEMBER_APPROVE,
    GUILD_MEMBER_GET,
    GUILD_MEMBER_KICK,
    GUILD_MEMBER_LIST,
    GUILD_MEMBER_MUTE,
    GUILD_MEMBER_ROLE_SET,
    GUILD_MEMBER_ROLE_UNSET,
    GUILD_ROLE_CREATE,
    GUILD_ROLE_DELETE,
    GUILD_ROLE_LIST,
    GUILD_ROLE_UPDATE,
    LOGIN_GET,
    MESSAGE_CREATE,
    MESSAGE_DELETE,
    MESSAGE_GET,
    MESSAGE_LIST,
    MESSAGE_UPDATE,
    REACTION_CLEAR,
    REACTION_CREATE,
    REACTION_DELETE,
    REACTION_LIST,
    USER_CHANNEL_CREATE,
    USER_GET,
    ChannelCreateParams,
    ChannelDeleteParams,
    ChannelGetParams,
    ChannelListParams,
    ChannelMuteParams,
    ChannelUpdateParams,
    Endpoint,
    FriendApproveParams,
    FriendDeleteParams,
    FriendListParams,
    GuildApproveParams,
    GuildGetParams,
    GuildListParams,
    GuildMemberApproveParams,
    GuildMemberGetParams,
    GuildMemberKickParams,
    GuildMemberListParams,
    GuildMemberMuteParams,
    GuildMemberRoleSetParams,
    GuildMemberRoleUnsetParams,
    GuildRoleCreateParams,
    GuildRoleDeleteParams,
    GuildRoleListParams,
    GuildRoleUpdateParams,
    MessageCreateParams,
    MessageDeleteParams,
    MessageGetParams,
    MessageListParams,
    MessageUpdateParams,
    ReactionClearParams,
    ReactionCreateParams,
    ReactionDeleteParams,
    ReactionListParams,
    UserChannelCreateParams,
    UserGetParams,
)
from .content_parser import (
    classify_content,
    clean_text,
    parse_attachments,
    parse_content,
    parse_mentions,
    to_llm_text,
)
from .enums import ChannelType, Direction, LoginStatus, Order
from .events import EventBody, LoginList, Signal
from .http import SatoriApiClient
from .ingress import SatoriMessageIngress
from .models import (
    Argv,
    BidiList,
    Button,
    Channel,
    Emoji,
    Friend,
    Guild,
    GuildMember,
    GuildRole,
    Login,
    Message,
    PageList,
    User,
)
from .websocket import SatoriClient

__all__ = [  # noqa: RUF022
    # enums
    "ChannelType", "Direction", "LoginStatus", "Order",
    # content parser
    "classify_content", "clean_text", "parse_attachments", "parse_content",
    "parse_mentions", "to_llm_text",
    # models
    "Argv", "BidiList", "Button", "Channel", "Emoji",
    "Friend", "Guild", "GuildMember", "GuildRole", "Login",
    "Message", "PageList", "User",
    # events
    "EventBody", "LoginList", "Signal",
    # api
    "CHANNEL_CREATE", "CHANNEL_DELETE", "CHANNEL_GET", "CHANNEL_LIST",
    "CHANNEL_MUTE", "CHANNEL_UPDATE",
    "ChannelCreateParams", "ChannelDeleteParams", "ChannelGetParams",
    "ChannelListParams", "ChannelMuteParams", "ChannelUpdateParams",
    "Endpoint",
    "FRIEND_APPROVE", "FRIEND_DELETE", "FRIEND_LIST",
    "FriendApproveParams", "FriendDeleteParams", "FriendListParams",
    "GUILD_APPROVE", "GUILD_GET", "GUILD_LIST",
    "GUILD_MEMBER_APPROVE", "GUILD_MEMBER_GET", "GUILD_MEMBER_KICK",
    "GUILD_MEMBER_LIST", "GUILD_MEMBER_MUTE",
    "GUILD_MEMBER_ROLE_SET", "GUILD_MEMBER_ROLE_UNSET",
    "GUILD_ROLE_CREATE", "GUILD_ROLE_DELETE", "GUILD_ROLE_LIST",
    "GUILD_ROLE_UPDATE",
    "GuildApproveParams", "GuildGetParams", "GuildListParams",
    "GuildMemberApproveParams", "GuildMemberGetParams",
    "GuildMemberKickParams", "GuildMemberListParams",
    "GuildMemberMuteParams", "GuildMemberRoleSetParams",
    "GuildMemberRoleUnsetParams",
    "GuildRoleCreateParams", "GuildRoleDeleteParams",
    "GuildRoleListParams", "GuildRoleUpdateParams",
    "LOGIN_GET",
    "MESSAGE_CREATE", "MESSAGE_DELETE", "MESSAGE_GET",
    "MESSAGE_LIST", "MESSAGE_UPDATE",
    "MessageCreateParams", "MessageDeleteParams", "MessageGetParams",
    "MessageListParams", "MessageUpdateParams",
    "REACTION_CLEAR", "REACTION_CREATE", "REACTION_DELETE", "REACTION_LIST",
    "ReactionClearParams", "ReactionCreateParams",
    "ReactionDeleteParams", "ReactionListParams",
    "USER_CHANNEL_CREATE", "USER_GET",
    "UserChannelCreateParams", "UserGetParams",
    # 传输客户端 + 事件归一化 + 平台适配器
    "SatoriAdapter", "SatoriApiClient", "SatoriClient", "SatoriMessageIngress",
]
